// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hello.proto

package hello

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hello service

func NewHelloEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hello service

type HelloService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Hello_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Hello_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Hello_BidiStreamService, error)
}

type helloService struct {
	c    client.Client
	name string
}

func NewHelloService(name string, c client.Client) HelloService {
	return &helloService{
		c:    c,
		name: name,
	}
}

func (c *helloService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Hello.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloService) ClientStream(ctx context.Context, opts ...client.CallOption) (Hello_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Hello.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloServiceClientStream{stream}, nil
}

type Hello_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type helloServiceClientStream struct {
	stream client.Stream
}

func (x *helloServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *helloServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *helloServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *helloService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Hello_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Hello.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &helloServiceServerStream{stream}, nil
}

type Hello_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type helloServiceServerStream struct {
	stream client.Stream
}

func (x *helloServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *helloServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *helloServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloService) BidiStream(ctx context.Context, opts ...client.CallOption) (Hello_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Hello.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloServiceBidiStream{stream}, nil
}

type Hello_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type helloServiceBidiStream struct {
	stream client.Stream
}

func (x *helloServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *helloServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *helloServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *helloServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hello service

type HelloHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Hello_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Hello_ServerStreamStream) error
	BidiStream(context.Context, Hello_BidiStreamStream) error
}

func RegisterHelloHandler(s server.Server, hdlr HelloHandler, opts ...server.HandlerOption) error {
	type hello interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Hello struct {
		hello
	}
	h := &helloHandler{hdlr}
	return s.Handle(s.NewHandler(&Hello{h}, opts...))
}

type helloHandler struct {
	HelloHandler
}

func (h *helloHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.HelloHandler.Call(ctx, in, out)
}

func (h *helloHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.HelloHandler.ClientStream(ctx, &helloClientStreamStream{stream})
}

type Hello_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type helloClientStreamStream struct {
	stream server.Stream
}

func (x *helloClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *helloHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HelloHandler.ServerStream(ctx, m, &helloServerStreamStream{stream})
}

type Hello_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type helloServerStreamStream struct {
	stream server.Stream
}

func (x *helloServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *helloHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.HelloHandler.BidiStream(ctx, &helloBidiStreamStream{stream})
}

type Hello_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type helloBidiStreamStream struct {
	stream server.Stream
}

func (x *helloBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *helloBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
